language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=pypy
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
install:
  - travis_retry pip install tox==1.6.1
script:
  - python tests/create_test_virtualenv.py
  - travis_retry tox
